name = "Cirno's perfect math class"
author = "hakureiyukari01@gmail.com"
category = "Misc"
description = "琪露诺发现幻想乡巴士里有base编码"
points = 50.0


attachment = "attachment/cpmc.zip"

[flag]
value = "flag{Gensokyo-has-no-bus-but-have-baka}"       # is empty stand for dynamic flag
env_var = "FLAG"
