name = "AI_shell"
author = "fb0sh@outlook.com"      # modify
category = "AI"                  # modify
description = "这个执行命令小模型，会听你的话吗？" # modify
points = 100.0

[flag]
value = ""       # is empty stand for dynamic flag # modify
env_var = "FLAG"


[docker]
image_tag = "ai_shell:latest" # modify
port = "80/tcp"
