name = "xzmu_anime_club"
author = "hakureiyukari01@gmail.com"
category = "Crypto"
description = "这里是西藏民族大学动漫社，欢迎来玩"


attachment = "attachment/xzmu.txt"

[flag]
value = "flag{929209409-739251410}"       # is empty stand for dynamic flag
env_var = "FLAG"