name = "ret2text"
author = "fb0sh@outlook.com" # modify
category = "Pwn" # modify
description = "return to text segment" # modify
points = 100.0

attachment = "attachment/ret2text"

[flag]
value = ""       # is empty stand for dynamic flag # modify
env_var = "FLAG"


[docker]
image_tag = "ret2text:latest" # modify
port = "1337/tcp"
is_nc = true
