name = "Flag_in_the_model"
author = "myx2727461997@gmail.com" # modify
category = "Misc" # modify
description = ".pt？这是什么后缀名？"

attachment = "attachment/Netron.pt" # modify

[flag]
value = "floatctf{0xdf2a78e_you_are_right!^v^}"       # is empty stand for dynamic flag # modify
env_var = "FLAG"

