name = "robots"
author = "myx2727461997@gmail.com"
category = "Web"
description = "听说搜索引擎的爬虫都会先看 robots.txt 文件？"

[flag]
value = ""
env_var = "FLAG"

[docker]
image_tag = "robots:latest"
port = "80/tcp"