name = "easy_reverse"
author = "ablklice@gmail.com"
category = "Reverse"
description = "使用tea算法进行解密,答案使用flag{}进行包裹"

attachment = "attachment/TEA.exe"

[flag]
value = "flag{c5e0f5f6f79e5b9b988f8f04611a7802}"       # is empty stand for dynamic flag
env_var = "FLAG"
