name = "FloatCTF-qidong"
author = "myx2727461997@gmail.com"
category = "Web"
description = "大喊FloatCTF启动来获得flag吧"
points = 100.0

[flag]
value = ""
env_var = "FLAG"

[docker]
image_tag = "floatctf-qidong:latest"
port = "80/tcp"
