name = "dir_enum"
author = "fb0sh@outlook.com"
category = "Web"
description = "想必你一定知道什么是目录扫描吧"


[flag]
value = ""       # is empty stand for dynamic flag
env_var = "FLAG"


[docker]
image_tag = "dir_enum:latest"
port = "80/tcp"
