name = "php_file"
author = "ablklice@gmail.com"
category = "Web"
description = "file伪协议"
points = 100.0                # for event

[flag]
value = ""       # is empty stand for dynamic flag
env_var = "FLAG"


[docker]
image_tag = "php_file:latest"
port = "80/tcp"
